# Generated by Django 5.1.4 on 2025-01-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_topic_category_remove_post_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
